### ISSUE TITLE
Addon not usable with Broadway 2t running firmware 3.3.1424

### ISSUE THREAD

**Issue by falcon03** [kodi-pvr/pvr.pctv#21] opened 2015-08-20 17:23 UTC
This PVR client does not work with a Broadway 2T running the latest firmware, version 3.3.1424. In fact, while the channel list is shown, the channels cannot be played at all.

**Comment by isklikas** [comment] 2022-03-07 19:06
I have the same issue and it's been 6 years since your post...

**Comment by phunkyfish** [comment] 2022-03-07 21:14
Can you supply a full debug log? This addon has no maintainer. So unless it is obvious what the issue is from the log I’m not sure how likely any fix might be.

**Comment by isklikas** [comment] 2022-03-07 22:41
> 

Yes of course. I made multiple attempts, occasionally it works if you enable transcoding, set a kbps rate and then it starts playing. But it’s only occasional, because neither all channels play and neither is it repeatable. Basically it’s a random trial and error where you change the kbps rate of the transcoding and it plays, but only once and for one random channel. I also included in the log the only successful attempt I had, along with every failed attempt.

Here’s the log: https://paste.kodi.tv/wuroquyajo.kodi

P.S. This might be irrelevant, but I also tried Next PVR and it also works, but again, only once. Next PVR appeared to not work because it couldn’t send a stop signal, because any stream would properly start, but I couldn’t start a new one after stopping the playback on the channel that was playing. A reboot would fix this error, or a manual start of a stream from their address on my smartphone. After the above, I could start any stream on Next PVR. The same does not apply to this plugin, but I believe the general issue is that neither plugin communicates properly with the device’s protocol, for different reasons.

**Comment by phunkyfish** [comment] 2022-03-08 07:48
I can't see it easily from the log but do you now what format the stream is? So when it actually plays if you look at the stream info `i` I think it should tell you. I could try setting the MIME type as part of the stream open as a test.

Also, I don't know what platform you have as your debug log is not complete.

**Comment by phunkyfish** [comment] 2022-03-08 08:09
Nexus PR: https://github.com/kodi-pvr/pvr.pctv/pull/109
Nexus Testbuilds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.pctv/detail/PR-109/1/artifacts

These set the MIME type to MpegTS.

**Comment by isklikas** [comment] 2022-03-20 14:50
Apologies, I only sent the parts I thought would be relevant last time. Here's the full log http://paste.kodi.tv/avukekicoc.kodi

I'm also sorry for the delay, I had to leave home for a trip and I couldn't test your build until now. For some reason however, I am unable to install it. I've also included this error as it appeared in my latest log, as well as a successful and a lot of unsuccessful playbacks. 

Thank you very much for your help!

**Comment by phunkyfish** [comment] 2022-03-20 16:09
You will need to run kodi nexus to try the test builds.

https://mirrors.kodi.tv/nightlies/

**Comment by isklikas** [comment] 2022-03-24 00:08
> You will need to run kodi nexus to try the test builds.
> 
> https://mirrors.kodi.tv/nightlies/

Yes, you fixed it! I tried every channel and it consistently works now, on every channel! There were no failed attempts, every channel played from the first attempt! Thank you so much! And once more, sorry for the late reply, I had a lot of work till late ever since I returned.

**Comment by phunkyfish** [comment] 2022-03-24 06:25
@isklikas

Amazing!!!


Ok, this is just a quick hack to see if it works. I’ll work on the proper fix and if you can test that on both Matrix and Nexus once ready that would be great.

**Comment by isklikas** [comment] 2022-03-24 07:47
Yes of course, once you complete your proper fix, I'll be happy to test them on both Matrix and Nexus! Thank you!

**Comment by phunkyfish** [comment] 2022-03-25 08:52
@isklikas here are testbuilds for the final version: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.pctv/detail/PR-109/2/artifacts

Two setting have been added: one a toggle to force the use of MPEG TS to stream. And another to set a custom MIME Type. The toggle should work on it's own. Please also test using the Default MIME Type, just try setting it to `video/mp2t`.

So out of the box after install it should fail, but with either used use as above it should work.

**Comment by isklikas** [comment] 2022-03-25 14:41
@phunkyfish Correct, I just checked all of the above scenarios, on Kodi Nexus! It does not work out of the box, but it works perfectly if I switch the toggle to on, or if I set the Default MIME Type to `video/mp2t`.

Thank you! Let me know if you make a Kodi Matrix build that you would like me to test.

**Comment by phunkyfish** [comment] 2022-03-26 09:29
Fixed for Nexus in: https://github.com/kodi-pvr/pvr.pctv/pull/109

**Comment by phunkyfish** [comment] 2022-03-26 09:46
I just had a good at the Matrix code. Unfortunately the add-on was changed in a considerable way so it's not easy to port the changes. So I think we leave this in Nexus and wait for the release of Kodi 20.

**Comment by isklikas** [comment] 2022-03-26 18:02
Sure, I believe you can close this issue then! Thank you very much! I'll be using Nexus until it's officially released as well!

**Closed** 2022-03-26 20:10 UTC
